Workspaces:
 - !Workspace
    repository: C:\Users\SLABIAD\vsCode_workspace\taxiNYK\TaxiNYK\wrk\workspace
Others:
    log_format: text
    archive_repo: C:\Users\SLABIAD\vsCode_workspace\taxiNYK\TaxiNYK\wrk\archive
    error_repo: C:\Users\SLABIAD\vsCode_workspace\taxiNYK\TaxiNYK\wrk\erreur
    log_repo: C:\Users\SLABIAD\vsCode_workspace\taxiNYK\TaxiNYK\wrk\log
         

