DevEntities:
- !DevEntity
    name: Location
    fields: 
        LocationID:
            type: Decimal
            taille: 100    
        Borough:
            type: Char
            taille: 100
        Zone:
            type: Char
            taille: 100
        Service_Zone:
            type: Char
            taille: 100
    business_key:
         - LocationID

Links: