Workspaces:
 - !Workspace
    repository: C:\Users\GELHAKMI\OneDrive - Micropole Group\Bureau\Tp_taxi\workspace
Others:
    log_format: text
    archive_repo: C:\Users\GELHAKMI\OneDrive - Micropole Group\Bureau\Tp_taxi\archive
    error_repo: C:\Users\GELHAKMI\OneDrive - Micropole Group\Bureau\Tp_taxi\error
    log_repo: C:\Users\GELHAKMI\OneDrive - Micropole Group\Bureau\Tp_taxi\log
         

