DevEntities:
 - !DevEntity
    name: Trip
    fields: 
        TripID:
            type: Char
            taille: 10
        VendorID:
            type: Char
            taille: 10
        PULocationID:
            type: Char
            taille: 30
        DOLocationID:
            type: Char
            taille: 30
        Trip_distance:
            type: Char
            taille: 30
        PaymentID:
            type: Char
            taille: 30
        RateCodeID:
            type: Char
            taille: 30
        tpep_pickup_datetime:
            type: Char
            taille: 30
        tpep_dropoff_datetime:
            type: Char
            taille: 30
    business_key:
         - TripID
         
Links:
  - !Link
    name: TripPaymentLocationVendor
    member: 
         Trip:
            business_key: 
                      TripID
            foreign_key: 
                    - TripID
         Location:
            business_key: 
                      LocationID
            foreign_key: 
                    - PULocationID
                    - DOLocationID                     
         Vendor:
            business_key: 
                      VendorID
            foreign_key: 
                    - VendorID
         Rate:
             business_key:
                     RateCodeID
             foreign_key: 
                    - RateCodeID        
         Payment:
             business_key:
                      PaymentID
             foreign_key:
                    - PaymentID