DevEntities: 
 - !DevEntity
    name: Payment
    fields: 
        Payment_type:
            type: Char
            taille: 50
        PaymentID:
            type: Char
            taille: 10
        
    business_key:
         - PaymentID
Links:
